import { motion } from "framer-motion";
import { Sparkles, Calculator, Lightbulb, BarChart3, Shield, TrendingUp, FileText, CheckCircle2 } from "lucide-react";

interface ParsedSection {
  number: number;
  title: string;
  lines: string[];
}

function getSectionIcon(title: string) {
  const lower = title.toLowerCase();
  if (lower.includes("recommend") || lower.includes("suggest") || lower.includes("improvement")) return Lightbulb;
  if (lower.includes("compar") || lower.includes("ratio") || lower.includes("score") || lower.includes("chart")) return BarChart3;
  if (lower.includes("tax") || lower.includes("calcul") || lower.includes("liabil") || lower.includes("income") || lower.includes("deduct")) return Calculator;
  if (lower.includes("compliance") || lower.includes("risk") || lower.includes("penalt") || lower.includes("require")) return Shield;
  if (lower.includes("saving") || lower.includes("benefit") || lower.includes("eligib") || lower.includes("credit") || lower.includes("invest")) return TrendingUp;
  if (lower.includes("status") || lower.includes("classif") || lower.includes("registr")) return CheckCircle2;
  return FileText;
}

function parseAIResult(text: string): ParsedSection[] {
  const sections: ParsedSection[] = [];
  const lines = text.split("\n");
  let current: ParsedSection | null = null;

  for (const line of lines) {
    const match = line.match(/^\*{0,2}\s*(\d+)\s*[.):\-]\s*\*{0,2}\s*(.+)/);
    if (match) {
      if (current) sections.push(current);
      const num = parseInt(match[1]);
      const title = match[2].replace(/\*{1,2}/g, "").replace(/:$/, "").trim();
      current = { number: num, title, lines: [] };
    } else if (current) {
      const cleaned = line.trim();
      if (cleaned) current.lines.push(cleaned);
    }
  }
  if (current) sections.push(current);
  return sections;
}

/** Detect if lines form a table (pipe-separated markdown table) */
function detectTable(lines: string[]): { isTable: boolean; headers: string[]; rows: string[][] } {
  const pipeLines = lines.filter(l => l.includes("|") && !l.match(/^\s*\|?[\s\-:|]+\|?\s*$/));
  const separatorLines = lines.filter(l => l.match(/^\s*\|?[\s\-:|]+\|?\s*$/));
  
  if (pipeLines.length >= 2 && separatorLines.length >= 1) {
    const parseRow = (row: string) =>
      row.split("|").map(c => c.trim()).filter(c => c.length > 0);
    
    const headers = parseRow(pipeLines[0]);
    const rows = pipeLines.slice(1).map(parseRow);
    return { isTable: true, headers, rows };
  }
  return { isTable: false, headers: [], rows: [] };
}

/** Render inline markdown: **bold** */
function renderInlineMarkdown(text: string) {
  const parts = text.replace(/^[-•*]\s*/, "").split(/(\*\*[^*]+\*\*)/g);
  return parts.map((part, i) =>
    part.startsWith("**") && part.endsWith("**") ? (
      <strong key={i} className="font-semibold text-gray-900">{part.slice(2, -2)}</strong>
    ) : (
      <span key={i}>{part}</span>
    )
  );
}

const accentColors = [
  "border-l-emerald-500",
  "border-l-blue-500",
  "border-l-violet-500",
  "border-l-amber-500",
  "border-l-rose-500",
  "border-l-cyan-500",
  "border-l-fuchsia-500",
  "border-l-lime-500",
];

const badgeBg = [
  "bg-emerald-500",
  "bg-blue-500",
  "bg-violet-500",
  "bg-amber-500",
  "bg-rose-500",
  "bg-cyan-500",
  "bg-fuchsia-500",
  "bg-lime-500",
];

export default function AIResultDisplay({ result }: { result: string }) {
  const sections = parseAIResult(result);
  const hasSections = sections.length >= 2;

  return (
    <div>
      {/* Header */}
      <div className="flex items-center gap-2 mb-5">
        <Sparkles className="w-5 h-5 text-primary" />
        <span className="text-sm font-semibold text-primary tracking-wide uppercase">AI Analysis Report</span>
      </div>

      {/* White report container */}
      <div className="rounded-2xl bg-white text-gray-800 shadow-xl overflow-hidden">
        <div className="px-6 py-5 border-b border-gray-200 bg-gray-50">
          <h4 className="text-lg font-bold text-gray-900">Analysis Results</h4>
          <p className="text-xs text-gray-500 mt-1">Generated by AI — for informational purposes only</p>
        </div>

        <div className="p-6 space-y-5">
          {hasSections ? (
            sections.map((section, i) => {
              const Icon = getSectionIcon(section.title);
              const table = detectTable(section.lines);
              const nonTableLines = table.isTable
                ? section.lines.filter(l => !l.includes("|") && !l.match(/^\s*\|?[\s\-:|]+\|?\s*$/))
                : section.lines;

              return (
                <motion.div
                  key={i}
                  className={`rounded-xl border border-gray-200 border-l-4 ${accentColors[i % accentColors.length]} bg-white shadow-sm overflow-hidden`}
                  initial={{ opacity: 0, y: 16 }}
                  animate={{ opacity: 1, y: 0 }}
                  transition={{ duration: 0.35, delay: i * 0.07 }}
                >
                  <div className="px-5 py-4">
                    {/* Section header */}
                    <div className="flex items-center gap-3 mb-3">
                      <div className={`w-8 h-8 rounded-full ${badgeBg[i % badgeBg.length]} flex items-center justify-center flex-shrink-0`}>
                        <span className="text-white text-sm font-bold">{section.number}</span>
                      </div>
                      <div className="flex items-center gap-2">
                        <Icon className="w-4 h-4 text-gray-400" />
                        <h5 className="text-base font-bold text-gray-900">{section.title}</h5>
                      </div>
                    </div>

                    {/* Table rendering */}
                    {table.isTable && (
                      <div className="overflow-x-auto mb-3">
                        <table className="w-full text-sm border-collapse">
                          <thead>
                            <tr className="bg-gray-50">
                              {table.headers.map((h, hi) => (
                                <th key={hi} className="text-left px-3 py-2 font-semibold text-gray-700 border border-gray-200">
                                  {renderInlineMarkdown(h)}
                                </th>
                              ))}
                            </tr>
                          </thead>
                          <tbody>
                            {table.rows.map((row, ri) => (
                              <tr key={ri} className={ri % 2 === 1 ? "bg-gray-50/50" : ""}>
                                {row.map((cell, ci) => (
                                  <td key={ci} className="px-3 py-2 text-gray-700 border border-gray-200">
                                    {renderInlineMarkdown(cell)}
                                  </td>
                                ))}
                              </tr>
                            ))}
                          </tbody>
                        </table>
                      </div>
                    )}

                    {/* Text content */}
                    {nonTableLines.length > 0 && (
                      <div className="text-sm text-gray-600 leading-relaxed space-y-1.5">
                        {nonTableLines.map((line, li) => {
                          const isBullet = /^[-•*]/.test(line) || /^[a-z]\)/.test(line);
                          return (
                            <p key={li} className={isBullet ? "pl-4 relative before:content-['•'] before:absolute before:left-0 before:text-gray-400" : ""}>
                              {renderInlineMarkdown(isBullet ? line.replace(/^[-•*]\s*/, "") : line)}
                            </p>
                          );
                        })}
                      </div>
                    )}
                  </div>
                </motion.div>
              );
            })
          ) : (
            /* Fallback for unstructured responses */
            <div className="text-sm text-gray-700 leading-relaxed whitespace-pre-line">
              {result}
            </div>
          )}
        </div>

        {/* Footer disclaimer */}
        <div className="px-6 py-3 bg-gray-50 border-t border-gray-200">
          <p className="text-[11px] text-gray-400 text-center">
            Disclaimer: This is AI-generated guidance and should not be considered as professional legal or financial advice.
          </p>
        </div>
      </div>
    </div>
  );
}
